### ISSUE TITLE
SSH2 Private Key Removal

### ISSUE THREAD

**Issue by nickstew** [Shmakov/Honeypot#1]
[etc/ssh2.private.key](/Shmakov/Honeypot/blob/master/etc/ssh2.private.key) should be removed as it is private info and this is a public repo.  RSA Keys (real or otherwise) should never live in a repository.

Great work on this project.  I really dig the live updates with the web sockets.  Keep up the amazing work!

**Comment by nickstew** [comment]
Oh, nevermind.  I just read through [your comment on Reddit](https://www.reddit.com/r/node/comments/8xrv8l/honeypot_written_in_nodejs_that_displays_real/e25bdbf/).

**Comment by Shmakov** [comment]
Thanks for looking into it Nick and keeping the repo safe :)
