### ISSUE TITLE
There is nothing in “Monthly Stats”

### ISSUE THREAD

**Issue by tao3323225** [Shmakov/Honeypot#2]
hi,there is nothing in my page of “Monthly Stats”，and where i can get the all events? thanks
Great work on this project!

**Comment by Shmakov** [comment]
Hi @tao3323225,

Monthly Stats will be present only if you are using optional MySQL configuration, you need to specify [mysql connection string](https://github.com/Shmakov/Honeypot/blob/master/config.js.template#L14) and create db schema based on the [mysql dump](https://github.com/Shmakov/Honeypot/blob/master/etc/mysql.db.schema.sql).

Please let me know if you have any questions.
